# 流程控制

## 条件与循环

js 语言的设计参考了 java 和 c 语言，流程控制基本与它们一致。包括

1. if
2. switch
3. while
4. 普通 for
5. for...in，遍历对象的所有**可枚举**属性，包括对象自身的属性和继承自原型链的**可枚举**属性，但是不包含 symbol。也可以用来遍历数字的索引和 map 的 key。
6. for...of，迭代器语法糖，只能迭代实现了迭代接口的对象。

## 异步循环

## 异常

js 中的异常处理机制也与 java 基本相同。

**引擎抛出异常**

引擎在执行 js 代码时，遇到异常会进行抛出。常见的几种情况：

1. 当代码执行到无法继续执行的语句时，比如访问未定义的变量、调用不存在的函数等，JavaScript 引擎会自动抛出一个 ReferenceError 异常。
2. 当发生语法错误时，JavaScript 引擎也会自动抛出一个 SyntaxError 异常。
3. 网络异常，Dom 异常等。

**throw 异常**

通过 throw 关键词，可以抛出一个异常。通常通过抛出自定义异常，附带更多信息。也可以直接抛出系统预定义好的几种异常。常见的有：Error、SyntaxError、ReferenceError、TypeError 等。

**异常捕获**

在 JavaScript 中，我们可以使用 try-catch 块来捕获和处理异常，如果在 try 块中抛出了异常，那么程序会立刻跳转到 catch 块中，并且异常对象会被赋值给 catch 块中的参数 e。如果没有编写 catch 块，或者 catch 块中的代码也抛出了异常，那么异常会继续向外传递，直到被处理或者导致程序崩溃。

除了 catch 块外，try-catch 块还可以配合 finally 块使用。finally 块中的代码会在 try-catch 块中的代码执行完毕后无论是否抛出异常都会被执行。如果 catch 中出现异常，finally 也会执行。

**全局异常处理**

在 JavaScript 中，可以通过在全局范围内注册一个 window.onerror 函数来处理全局异常。会在全局范围内捕获到**未被处理**的异常时被调用，可以通过这个函数对异常进行统一的处理。

**异常未处理的后果**

如果发生未被处理的异常，会导致当前的脚本执行被中止，但并不会导致整个网页崩溃。当异常被抛出时，如果没有被及时捕获和处理，会导致当前脚本执行被中止。如果异常发生在全局范围内，会导致整个脚本的执行被中止，但并不会导致整个网页崩溃。其他页面元素和脚本仍然可以正常运行，用户可以继续与网页进行交互。

**异常捕获原理**

在 JavaScript 中，异常捕获的原理基本上可以分为两个步骤：

抛出异常：当 JavaScript 引擎遇到一个异常（比如运行时错误或语法错误）时，会生成一个异常对象并将其抛出（throw）。抛出异常会中断当前代码的执行，并且会导致执行流程跳转到当前代码所在的最近的异常处理程序（try-catch 或者全局异常处理器）。

捕获异常：当异常被抛出后，JavaScript 引擎会依次查找当前代码所在的函数、函数调用链、以及全局作用域，以查找能够处理该异常的 try-catch 块。如果找到了匹配的 catch 块，则会执行该块中的代码，并将该块的参数设置为异常对象。如果没有找到匹配的 catch 块，则该异常会被传递到调用栈的上一层，并重复上述查找过程，直到找到匹配的 catch 块或者到达全局作用域。如果最终还是没有找到匹配的 catch 块，则该异常会成为未捕获的异常，将会导致当前脚本执行被中止。
